### ISSUE TITLE
Basic Rules

### ISSUE THREAD

**Issue by MohammadAlHabil** [GSG-G11/Social-Posts#2]
### Color
```html
<html lang="en" data-theme="light">
```
```CSS 
:root{
--white: #ffffff;
--main: #399DF5;
--background: #F0F5FB;
--font: #212226;
--placeholder: #808080;
--yellow: #FDEA81;
--red: #F85F61;
--purple: #877BFB;
--sec-blue: #2ED0F7;
}
```
### Font
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Readex+Pro:wght@200;300;400;500;600;700&family=Yeseva+One&display=swap" rel="stylesheet">
```
- Use this font in CSS 

> 
```CSS 
font-family: 'Readex Pro', sans-serif;
```

### Icon [link](https://pro.fontawesome.com/releases/v5.10.0/css/all.css)
```html
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
```
```CSS 
<i class="far fa-persone"></i>
```
